#!/bin/bash
# =============================================================================
# Shipyard - Caddy Configuration Generator
# =============================================================================
# Generates a Caddyfile and installs it. Supports:
#   - Primary domain with reverse proxy
#   - WWW redirect
#   - Subdomains with optional path prefix rewriting
#   - WebSocket passthrough
#
# Usage:
#   bash setup-caddy.sh --domain example.com --subdomains "www,app,api" --port 8080
#
# Advanced (with path prefixes):
#   bash setup-caddy.sh --domain example.com \
#     --subdomains "www:redirect,wedding:/wedding,games:/games:ws" \
#     --port 8080
#
# Subdomain format: name[:path_prefix][:ws]
#   - "www:redirect"      → redirects to primary domain
#   - "app:/app"          → rewrites paths with /app prefix
#   - "games:/games:ws"   → path rewrite + WebSocket support at /ws/*
#   - "api"               → simple reverse proxy, no rewriting
# =============================================================================

set -e

# =============================================================================
# Parse arguments
# =============================================================================
DOMAIN=""
SUBDOMAINS=""
PORT=8080

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain) DOMAIN="$2"; shift 2 ;;
    --subdomains) SUBDOMAINS="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [ -z "$DOMAIN" ]; then
  echo "Error: --domain is required"
  exit 1
fi

CADDYFILE="/etc/caddy/Caddyfile"

echo "Generating Caddyfile for $DOMAIN..."

# =============================================================================
# Primary domain
# =============================================================================
cat > "$CADDYFILE" <<EOF
# Generated by Shipyard
# Domain: $DOMAIN
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

$DOMAIN {
    reverse_proxy localhost:$PORT
}
EOF

# =============================================================================
# Process subdomains
# =============================================================================
if [ -n "$SUBDOMAINS" ]; then
  IFS=',' read -ra SUBS <<< "$SUBDOMAINS"
  for sub_config in "${SUBS[@]}"; do
    sub_config=$(echo "$sub_config" | xargs)  # trim whitespace
    
    # Parse subdomain config: name[:path_prefix][:ws]
    IFS=':' read -ra PARTS <<< "$sub_config"
    SUB_NAME="${PARTS[0]}"
    PATH_PREFIX="${PARTS[1]:-}"
    WS_FLAG="${PARTS[2]:-}"

    # WWW redirect
    if [ "$SUB_NAME" = "www" ] || [ "$PATH_PREFIX" = "redirect" ]; then
      cat >> "$CADDYFILE" <<EOF

$SUB_NAME.$DOMAIN {
    redir https://$DOMAIN{uri} permanent
}
EOF
      continue
    fi

    # Simple proxy (no path prefix)
    if [ -z "$PATH_PREFIX" ]; then
      cat >> "$CADDYFILE" <<EOF

$SUB_NAME.$DOMAIN {
    reverse_proxy localhost:$PORT
}
EOF
      continue
    fi

    # Subdomain with path prefix rewriting
    cat >> "$CADDYFILE" <<EOF

$SUB_NAME.$DOMAIN {
    @static path /css/* /js/* /img/* /json/* /favicon.ico /audio/*
    handle @static {
        reverse_proxy localhost:$PORT
    }
EOF

    # Add WebSocket handler if flagged
    if [ "$WS_FLAG" = "ws" ]; then
      cat >> "$CADDYFILE" <<EOF
    handle /ws/* {
        reverse_proxy localhost:$PORT
    }
EOF
    fi

    # Root and catch-all with path rewrite
    cat >> "$CADDYFILE" <<EOF
    handle / {
        rewrite * $PATH_PREFIX
        reverse_proxy localhost:$PORT
    }
    handle {
        rewrite * $PATH_PREFIX{path}
        reverse_proxy localhost:$PORT
    }
}
EOF
  done
fi

# =============================================================================
# Validate and restart
# =============================================================================
echo "Validating Caddyfile..."
caddy validate --config "$CADDYFILE" 2>/dev/null && echo "  ✅ Valid" || echo "  ⚠️  Validation failed (Caddy may not be running yet, will work on restart)"

echo "Restarting Caddy..."
systemctl restart caddy 2>/dev/null || echo "  Note: Caddy service not running yet. Will start on first request."

echo ""
echo "✅ Caddyfile installed at $CADDYFILE"
echo ""
echo "Contents:"
echo "---"
cat "$CADDYFILE"
echo "---"
